name: Automatically build and run tests
on:
  push

jobs:
  build:
      name: Build and Run Tests
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [12.x, 14.x]
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Setup Node
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node-version }}
        - name: Install Yarn packages
          run: yarn install
        - name: Build code
          run: yarn build
        - name: Run Tests
          run: yarn test